### ISSUE TITLE
stop using `unwrap()` in value parsers

### ISSUE THREAD

**Issue by achristmascarl** [achristmascarl/rainfrog#108]
## description
the value parsers for the db drivers uses unwrap a lot

## proposed solution
maybe fall back to an empty string or something else to indicate if the type can't be cast to a string

**Comment by platlas** [comment]
I just tried with sqlite file saved from QGis and it crashed  here:
https://github.com/achristmascarl/rainfrog/blob/0159133eda01ca9fb6ddfd7de9d71dca5899d524/src/database/sqlite.rs#L125

on table that has column of type `MULTIPOLYGON`. I think sqlx does not support that type, but it would be nice if it just ignored those values and displayed other columns.

**Comment by achristmascarl** [comment]
@platlas let me know if you have a chance to test this with the MULTIPOLYGON type after the new release and if it still crashes 🙏

**Comment by platlas** [comment]
It works now without crashes. Thanks!
