### ISSUE TITLE
rainfrog Crash Report

### ISSUE THREAD

**Issue by mstrug** [achristmascarl/rainfrog#129]
## bug description
Panic when editing sql query.

### system info
 - OS: Linux Debian 12 running in WSL (Windows 11)
 - rainfrog version: 0.2.9
 - terminal emulator and shell: bash in WSL console (Windows cmd)

### crash logs
name = "rainfrog"
operating_system = "Debian 12.0.0 [64-bit]"
crate_version = "0.2.9"
explanation = """
Panic occurred in file '/home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui-textarea-0.6.1/src/history.rs' at line 56"""
cause = "slice index starts at 1 but ends at 0"
method = "Panic"
backtrace = """

   0: 0x5636f2c7b1f4 - tui_textarea::history::EditKind::apply::hc45fe6b1df292d33
   1: 0x5636f2c73564 - tui_textarea::textarea::TextArea::insert_chunk::h2dccda10296bd5c3
   2: 0x5636f2c748b8 - tui_textarea::textarea::TextArea::paste::h211e652e1a7bbdae
   3: 0x5636f26420e8 - rainfrog::components::editor::Editor::transition_vim_state::h1516b0777dc51056
   4: 0x5636f264ad6f - <rainfrog::components::editor::Editor as rainfrog::components::Component<DB>>::handle_events::h2d866a6dd1c67cd   5: 0x5636f25e0455 - rainfrog::app::App<DB>::run::{{closure}}::h8fab0460955e5016
   6: 0x5636f25cf9aa - rainfrog::main::{{closure}}::hadd3e05f01c649b6
   7: 0x5636f264f9ed - rainfrog::main::h34777ad25b20d86e
   8: 0x5636f2729443 - std::sys::backtrace::__rust_begin_short_backtrace::he5cbf5b86167bb0b
   9: 0x5636f264f1a2 - main
  10: 0x7fa7dd15424a - __libc_start_call_main
                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
  11: 0x7fa7dd154305 - __libc_start_main_impl
                at ./csu/../csu/libc-start.c:360
  12: 0x5636f23b6b01 - _start
  13:        0x0 - <unresolved>"""

### steps to reproduce
I was editing sql query, possibly pressing some wrong key. I'm unable to reproduce it.

### expected behavior
No crash occurs.

**Comment by achristmascarl** [comment]
from the logs it looks like the last event before the crash was a paste, do you know what the contents might have been?

**Comment by mstrug** [comment]
I'm sorry but I don't know. I was trying to paste some possible texts now but without any issues. It is possible that I've pressed some key combination accidentally.

**Comment by achristmascarl** [comment]
no worries; i didn't see anything about this upstream in https://github.com/rhysd/tui-textarea either, so i'll close it for now but will reopen if someone runs into it again
