### ISSUE TITLE
Table names need to be double quoted `public.TableName` -> `public."TableName"` in auto generated queries to handle table names with capital letters

### ISSUE THREAD

**Issue by kyruzic** [achristmascarl/rainfrog#29]
To handle table names that contain capitalization double quotes around the table name are required 

this fails

```sql
SELECT * FROM public.MyTable
```

But this succeeds 

```sql
SELECT * FROM public."MyTable"
```

You can do this to all table names without worry because on lower cased table names it changes nothing. 

BTW the project is awesome, if I have some time in the near future I'll help you out with it.

**Comment by kyruzic** [comment]
Specifically talking about the "rows" query here, but you may have other queries like it that you generate where this would also apply.

**Comment by achristmascarl** [comment]
thanks for the fix!
