### ISSUE TITLE
ContentNotAvailable - "The clipboard contents were not available in the requested format or the clipboard is empty."

### ISSUE THREAD

**Issue by rockerBOO** [achristmascarl/rainfrog#79]
## bug description
I tried to yank `y` from the results into the query section. 
Was using `p` to paste and it crashed. 

I'm on *Wayland* so maybe the clipboard is different than X11. 

### system info
 - Linux  6.10.7-arch1-1 GNU/Linux
 - rainfrog 0.2.0-VERGEN_IDEMPOTENT_OUTPUT (2024-09-17)

### crash logs
```sh
name = "rainfrog"
operating_system = "Arch Linux Rolling Release [64-bit]"
crate_version = "0.2.0"
explanation = """
Panic occurred in file 'src/vim.rs' at line 143
"""
cause = 'called `Result::unwrap()` on an `Err` value: ContentNotAvailable - "The clipboard contents were not available in the requested format or the clipboard is empty."'
method = "Panic"
backtrace = """

   0: 0x5be53d1f11dc - <unresolved>
   1: 0x5be53d1f1a0e - <unresolved>
   2: 0x5be53d07d6c8 - <unresolved>
   3: 0x5be53d1ad623 - <unresolved>
   4: 0x5be53d10cc36 - <unresolved>
   5: 0x5be53d1acd5c - <unresolved>
   6: 0x77b56ef2ce08 - <unresolved>
   7: 0x77b56ef2cecc - __libc_start_main
   8: 0x5be53ce6c185 - <unresolved>
   9:        0x0 - <unresolved>"""

```

### steps to reproduce
Steps to reproduce the behavior. If possible, include the preceding query with sensitive information removed:
1. Make any query that produces results
2. Go to results and yank (y)
3. Go to the query and paste (p)

Also must be on Wayland probably. 

### expected behavior
Pasted results in query.

**Comment by achristmascarl** [comment]
thanks for the report. looks like i may need to enable a feature flag for arboard: https://github.com/1Password/arboard/issues/98

**Comment by achristmascarl** [comment]
@rockerBOO and/or @elipp, when you have a moment, could you see if the code on the main branch fixes this for you? i dont have a way to test on wayland at the moment

**Comment by achristmascarl** [comment]
it's also released in v0.2.1

**Comment by rockerBOO** [comment]
Working for me, thank you. Will report if the released version isn't fixed. 

Thanks!

**Comment by elipp** [comment]
Closed already, but works for me too =)

**Comment by bjesus** [comment]
It actually doesn't work for me on Sway. whenever I'm trying to copy there's some "broken pipe" text printed on top of rainfrog, but the text isn't copied.

**Comment by achristmascarl** [comment]
@bjesus ah interesting; could you open a new issue with screenshots / the logs from `$XDG_DATA_HOME/<project_path> or $HOME/.local/share/<project_path>` if possible? i don't have a good way to test with wayland at the moment but i can take a look 🙏
