### ISSUE TITLE
Jump through pages of results

### ISSUE THREAD

**Issue by rgmz** [achristmascarl/rainfrog#82]
## description
The results pane supports "next/prev row" and "top/bottom" but does not seem to support pagination. (Unless it's bound to different key(s) and I somehow missed it.) 

## proposed solution
It would be useful to be able to scroll by page with "Page Up" and "Page Down", similar to what you can do with Vim or psql.

-------
P.S., Cool project!

**Comment by achristmascarl** [comment]
i like that idea! and thank you :)
