### ISSUE TITLE
fix X11 clipboard timeout on linux

### ISSUE THREAD

**Issue by achristmascarl** [achristmascarl/rainfrog#83]
## bug description
first reported in https://github.com/achristmascarl/rainfrog/issues/77, it seems like arboard's clipboard creation takes to long with X11 (more details: https://github.com/1Password/arboard/issues/153). This was reported on ubuntu 20 and reproduced in ubuntu 22 and also arch

## technical details
this was patched in https://github.com/achristmascarl/rainfrog/pull/81, but falling back to the textarea buffer means the data doesn't make it to the user's actual clipboard. it looks like extending the timeout for creating the Clipboard instance might help (https://github.com/1Password/arboard/pull/147), but will need to test that out to verify

### system info
 - OS version and architecture (can be obtained by running `uname` in your terminal): ubuntu 20, ubuntu 22, and whatever arch latest is as of 9/17/2024. all 64 bit
 - rainfrog version (available in crash logs or by running `rainfrog --version`): v0.2.0

### expected behavior
arboard works on linux

**Comment by LucasGarciaSI** [comment]
### Possível Solução
Você pode implementar a sugestão de aumentar o tempo limite na criação da área de transferência:

```go
func CreateClipboardInstance() error {
    timeout := 500 * time.Millisecond // Aumentar o timeout conforme necessário
    clipboardInstance, err := NewClipboard(timeout)
    if err != nil {
        return fmt.Errorf("falha ao criar a instância da área de transferência: %v", err)
    }
    return nil
}
