### ISSUE TITLE
Can't type the letter 'q' in the query editor

### ISSUE THREAD

**Issue by elipp** [achristmascarl/rainfrog#86]
## bug description
Can't type the letter 'q' in the query editor. Probably some key binding blocks it, but should work in the vi insert mode

### system info
- arch linux x86-64/Linux 6.10/Wayland
- rainfrog 0.2.1

### crash logs
no crash

### steps to reproduce
Go to query editor, enter insert mode, press (lower case) q.

### expected behavior
A lower case q should appear :D

**Comment by achristmascarl** [comment]
thx for the report; does this happen all the time, or only when there's a query running?

when there's a query running [q] aborts the query

**Comment by achristmascarl** [comment]
actually i was able to repro, apparently the default keybindings have allowed this to happen all along.... no idea how i never caught this lol

**Comment by elipp** [comment]
noice
